---
apiVersion: v1
kind: Service
metadata:
  name: event-client
  namespace: service
  labels:
    app: event-client
  annotations:
    ingress.kubernetes.io/service-upstream: "true"
spec:
  type: ClusterIP
  ports:
    - port: 6001
      targetPort: 6001
      protocol: TCP
  selector:
    app: event-client
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: event-client
  namespace: service
automountServiceAccountToken: true
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: event-client
  namespace: service
spec:
  protocol: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-client
  namespace: service
spec:
  replicas: 1
  selector:
    matchLabels:
      service: event-client
      app: event-client
  template:
    metadata:
      labels:
        service: event-client
        app: event-client
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
        'consul.hashicorp.com/service-meta-version': 'v1'
        consul.hashicorp.com/connect-service-upstreams: 'event-server:50051'
    spec:
      serviceAccountName: event-client
      containers:
        - name: event-client
          image: supanuttangsin/event-client-svc:latest
          imagePullPolicy: Always
          env:
          - name: GRPC_SERVER_PORT
            value: 
          - name: HTTP_PORT
            value: 
          - name: JWT_SECRET
            value: 
          - name: FRONTEND_ROUTE
            value: 
          ports:
            - containerPort: 6001
          livenessProbe:
            httpGet:
              path: /health
              port: 6001
            initialDelaySeconds: 15
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: 6001
            initialDelaySeconds: 10
            periodSeconds: 10
---