---
apiVersion: v1
kind: Service
metadata:
  name: notification
  namespace: service
  labels:
    app: notification
  annotations:
    ingress.kubernetes.io/service-upstream: "true"
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
  selector:
    app: notification
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: notification
  namespace: service
automountServiceAccountToken: true
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: notification
  namespace: service
spec:
  protocol: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  namespace: service
spec:
  replicas: 1
  selector:
    matchLabels:
      service: notification
      app: notification
  template:
    metadata:
      labels:
        service: notification
        app: notification
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
        'consul.hashicorp.com/service-meta-version': 'v1'
        consul.hashicorp.com/connect-service-upstreams: 'rabbitmq:5672'
    spec:
      serviceAccountName: notification
      containers:
        - name: notification
          image: supanuttangsin/notification-svc:latest
          imagePullPolicy: Always
          env:
          - name: MONGOURI
            value: 
          - name: APP_PASSWORD
            value:
          - name: RABBITMQ_CONNECTION
            value: 
          ports:
          - containerPort: 8081
          - containerPort: 8082
          livenessProbe:
            httpGet:
              path: /health
              port: 8082
            initialDelaySeconds: 15
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: 8082
            initialDelaySeconds: 10
            periodSeconds: 10
---