---
apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: service
  labels:
    app: user
  annotations:
    ingress.kubernetes.io/service-upstream: "true"
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    app: user
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: user
  namespace: service
automountServiceAccountToken: true
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: user
  namespace: service
spec:
  protocol: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: service
spec:
  replicas: 1
  selector:
    matchLabels:
      service: user
      app: user
  template:
    metadata:
      labels:
        service: user
        app: user
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
        'consul.hashicorp.com/service-meta-version': 'v1'
    spec:
      serviceAccountName: user
      containers:
        - name: user
          image: supanuttangsin/user-svc:latest
          imagePullPolicy: Always
          env:
          - name: NODE_ENV
            value: 
          - name: PORT
            value: 
          - name: DATABASE_URL
            value: 
          - name: GOOGLE_CLIENT_ID
            value: 
          - name: GOOGLE_CLIENT_SECRET
            value: 
          - name: GOOGLE_REDIRECT_URL
            value: 
          - name: GOOGLE_REDIRECT_URL_CLIENT
            value:
          - name: JWT_SECRET
            value: 
          - name: NODE_TLS_REJECT_UNAUTHORIZED
            value:
          - name: CLIENT_URL
            value: 
          ports:
            - containerPort: 5000
          livenessProbe:
            httpGet:
              path: /health/service
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health/database
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
---