global:
  enabled: true
  name: consul
  image: "hashicorp/consul:1.19.2"
  acls:
    manageSystemACLs: true
  tls:
    enabled: true
    enableAutoEncrypt: true
    verify: true

server:
  enabled: true
  replicas: 1
  bootstrapExpect: 1
  extraConfig: |
    {
      "log_level": "DEBUG"
    }

client:
  enabled: true

connectInject:
  transparentProxy:
    defaultEnabled: true
  enabled: true
  default: true 

controller:
  enabled: true

ui:
  enabled: true
  service:
    enabled: true
    type: LoadBalancer

dns:
  enabled: true
  proxy: true