---
apiVersion: v1
kind: Service
metadata:
  name: kong
  namespace: service
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  - name: https
    port: 8443
    targetPort: 8443
  - name: admin-http
    port: 8001
    targetPort: 8001
  - name: admin-https
    port: 8444
    targetPort: 8444
  - name: gui
    port: 8002
    targetPort: 8002
  - name: status
    port: 8100
    targetPort: 8100
  selector:
    app: kong
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kong
  namespace: service
automountServiceAccountToken: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong
  namespace: service
spec:
  replicas: 1
  selector:
    matchLabels:
      service: kong
      app: kong
  template:
    metadata:
      labels:
        service: kong
        app: kong
      annotations:
        consul.hashicorp.com/connect-inject: 'true'
        consul.hashicorp.com/transparent-proxy: 'false'
        consul.hashicorp.com/connect-service-upstreams: 'app-a:3000,club:8080,user:5000,event-client:6001'
    spec:
      serviceAccountName: kong
      containers:
      - name: kong
        image: supanuttangsin/kong-api-gateway:latest
        securityContext:
          runAsUser: 0
        env:
        - name: KONG_PG_DATABASE
          valueFrom:
            configMapKeyRef:
              name: kong-config
              key: KONG_PG_DATABASE
        - name: KONG_PG_HOST
          valueFrom:
            configMapKeyRef:
              name: kong-config
              key: KONG_PG_HOST
        - name: KONG_PG_USER
          valueFrom:
            configMapKeyRef:
              name: kong-config
              key: KONG_PG_USER
        - name: KONG_PG_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: kong-config
              key: KONG_PG_PASSWORD
        - name: KONG_ADMIN_ACCESS_LOG
          value: 
        - name: KONG_ADMIN_ERROR_LOG
          value: 
        - name: KONG_PROXY_LISTEN
          value: 
        - name: KONG_ADMIN_LISTEN
          value: 
        - name: KONG_STATUS_LISTEN
          value:
        - name: KONG_ADMIN_GUI_LISTEN
          value: 
        - name: KONG_PROXY_ACCESS_LOG
          value:
        - name: KONG_PROXY_ERROR_LOG
          value:
        - name: KONG_PREFIX
          value:
        - name: KONG_DECLARATIVE_CONFIG
          value: 
        - name: KONG_LOG_LEVEL
          value: 
        - name: KONG_PLUGINSERVER_NAMES
          value: 
        - name: KONG_PLUGINSERVER_JS_SOCKET
          value: 
        - name: KONG_PLUGINSERVER_JS_START_CMD
          value: 
        - name: KONG_PLUGINSERVER_JS_QUERY_CMD
          value: 
        - name: KONG_PLUGINS
          value: 
        ports:
        - containerPort: 8000
        - containerPort: 8443
        - containerPort: 8001
        - containerPort: 8444
        - containerPort: 8002
        - containerPort: 8100
        volumeMounts:
        - name: kong-prefix-vol
          mountPath: /var/run/kong
        - name: kong-tmp-vol
          mountPath: /tmp
        livenessProbe:
          httpGet:
            path: /status
            port: 8100
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /status/ready
            port: 8100
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
      - name: kong-prefix-vol
        persistentVolumeClaim:
          claimName: kong-prefix-vol-claim
      - name: kong-tmp-vol
        persistentVolumeClaim:
          claimName: kong-tmp-vol-claim
      restartPolicy: Always
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: kong
  namespace: service
spec:
  protocol: http