apiVersion: v1
kind: PersistentVolume
metadata:
  name: kong-prefix-vol
  labels:
    type: local
    app: kong-prefix-vol
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /var/run/kong
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kong-prefix-vol-claim
  labels:
    app: kong-prefix-vol
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---


apiVersion: v1
kind: PersistentVolume
metadata:
  name: kong-tmp-vol
  labels:
    type: local
    app: kong-tmp-vol
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /tmp
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kong-tmp-vol-claim
  labels:
    app: kong-tmp-vol
  # namespace: kong
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---