
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kong-migrations
automountServiceAccountToken: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong-migrations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong-migrations
  template:
    metadata:
      labels:
        app: kong-migrations
      annotations:
        consul.hashicorp.com/connect-inject: 'false'
    spec:
      serviceAccountName: kong-migrations
      containers:
      - name: kong-migrations
        image: kong:3.6
        command: ["kong", "migrations", "bootstrap"]
        env:
        - name: KONG_PG_DATABASE
          valueFrom:
            configMapKeyRef:
              name: kong-config
              key: KONG_PG_DATABASE
        - name: KONG_PG_HOST
          valueFrom:
            configMapKeyRef:
              name: kong-config
              key: KONG_PG_HOST
        - name: KONG_PG_USER
          valueFrom:
            configMapKeyRef:
              name: kong-config
              key: KONG_PG_USER
        - name: KONG_PG_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: kong-config
              key: KONG_PG_PASSWORD
        ports:
        - containerPort: 8000
        - containerPort: 8001
        - containerPort: 8443
        - containerPort: 8444
      restartPolicy: Always
