apiVersion: v1
kind: PersistentVolume
metadata:
  name: kong-data
  namespace: service
  labels:
    type: local
    app: kong-data
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /var/lib/postgresql/data/pgdata
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kong-data-claim
  namespace: service
  labels:
    app: kong-data
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
